import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Quote from '@/components/Quote';
import About from '@/components/About';
import Skills from '@/components/Skills';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yassar Rich Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>
      <Header></Header>
      <Quote></Quote>
      
      <main className=" bg-grey-100 px-10  dark:bg-gray-900">
        <p className=' text-black dark:text-white'><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className='cursor-pointer text-2xl text-black dark:text-white'/>Easter Egg</p>
        
      <div id="#about">
       <About ></About>
       </div>

      <div id="#skills">
      <Skills></Skills>
      </div>

      <div id="#projects">
      <Projects></Projects>
      </div>

      <div id="#contact">
      <Contact></Contact>
      </div>   
      </main>
      <Footer></Footer>
    </div>

  )
}
