import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillLinkedin, 
  AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import headshot from "/Users/yassarrich/Desktop/newPortfolio/my-app/public/headshot.jpg";
import skills from "/Users/yassarrich/Desktop/newPortfolio/my-app/public/skills.png";
import code from "/Users/yassarrich/Desktop/newPortfolio/my-app/public/code.png";
import { useState } from 'react';
import Header from '@/Header';
import Footer from '@/Footer';
import Quote from '@/Quote';
import About from '@/About';
import Skills from '@/Skills';
import Projects from '@/Projects';
import Contact from '@/Contact';

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yassar Rich Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Quote></Quote>
      
      <main className=" bg-black px-10  dark:bg-gray-900">
        <p><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className='cursor-pointer text-2xl text-black dark:text-white'/></p>
       <About href="#about"></About>
      <Skills href="skills"></Skills>
      <Projects href="#projects"></Projects>
      <Contact href="#contact"></Contact>     

      </main>
      <Footer></Footer>
    </div>

  )
}
